### ISSUE TITLE
ERROR Swoole short name have to disable before start server, please set swoole.use_shortname = 'Off' into your php.ini.

### ISSUE THREAD

**Issue by PandaLIU-1111** [buexplain/go-watch#1]
`swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.3
Built => Aug  7 2019 10:50:26
coroutine => enabled
kqueue => enabled
rwlock => enabled
http2 => enabled
pcre => enabled
zlib => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 262144 => 262144`

请问为什么还是会报错，需要设置swoole.use_shortname = Off

**Comment by ha-ni-cc** [comment]
php.ini加一行
swoole.use_shortname = "Off"
